version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_US: postgres
      POSTGRES_PASSWORD: 123
      POSTGRED_DB: nest
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    networks:
      - firstnest
networks:
  firstnest: